language: python
dist: focal
python:
  - 3.10

services:
  - docker

env:
  - MINIO_ROOT_USER=minioadmin MINIO_ROOT_PASSWORD=minioadmin MINIO_URL=http://localhost:9000 MINIO_ACCESS_KEY=minioadmin MINIO_SECRET_KEY=minioadmin HTSGET_TEST_KEY=thisisatest USE_MINIO_SANDBOX=True DB_PATH=localhost SERVER_LOCAL_DATA=/home/travis/build/CanDIG/htsget_app/data PGPASSWORD=OG0pjmnQDWUTvLotYrxPrg PGUSER=admin INDEXING_PATH=/home/travis/build/CanDIG/tmp

before_install:
  - docker pull minio/minio
  - docker create -p9090:9090 -p9000:9000 -p9001:9001 minio/minio minio server /data | xargs -I{} docker start {}
  - docker pull postgres:15-alpine
  - docker create -p5433:5432 -p5432:5432 --env POSTGRES_USER=admin --env POSTGRES_DB=metadata --env POSTGRES_PASSWORD=OG0pjmnQDWUTvLotYrxPrg --env POSTGRES_HOST_AUTH_METHOD=password --name metadata-db postgres:15-alpine | xargs -I{} docker start {}
  - docker ps -a
  - docker logs metadata-db

cache: pip
install:
  - pip install -r requirements.txt
  - bash create_db.sh
  - mkdir -p $INDEXING_PATH

script:
  - python htsget_server/server.py &
  - python htsget_server/indexing.py &
  - sleep 5
  - pytest tests/test_htsget_server.py
