language: python
dist: focal
python:
  - 3.12

services:
  - docker

env:
  - HTSGET_TEST_KEY=thisisatest DB_PATH=localhost SERVER_LOCAL_DATA=/home/travis/build/CanDIG/htsget_app/data PGPASSWORD=OG0pjmnQDWUTvLotYrxPrg PGUSER=admin INDEXING_PATH=/home/travis/build/CanDIG/tmp TESTENV_URL=http://localhost:3000 AGGREGATE_COUNT_THRESHOLD=5

before_install:
  - docker pull postgres:15-alpine
  - docker create -p5433:5432 -p5432:5432 --env POSTGRES_USER=admin --env POSTGRES_DB=metadata --env POSTGRES_PASSWORD=OG0pjmnQDWUTvLotYrxPrg --env POSTGRES_HOST_AUTH_METHOD=password --name metadata-db postgres:15-alpine | xargs -I{} docker start {}
  - docker ps -a
  - docker logs metadata-db

cache: pip
install:
  - pip install -r requirements.txt
  - bash create_db.sh
  - mkdir -p $INDEXING_PATH

script:
  - sed -i s@\<AGGREGATE_COUNT_THRESHOLD\>@$AGGREGATE_COUNT_THRESHOLD@ config.ini
  - python htsget_server/server.py &
  - python htsget_server/indexing.py &
  - sleep 5
  - pytest tests/test_htsget_server.py
