language: python
python:
  - 3.6

cache: pip
install:
  - python setup.py install
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt

script:
  - python htsget_server/server.py &
  - sleep 5
  - pytest tests/test_htsget_server.py

env:
  - HTSGET_TEST_KEY=thisisatest USE_MINIO_SANDBOX=True
  