language: python
python:
  - 3.7

cache: pip
install:
  - pip install -r requirements.txt

script:
  - python htsget_server/server.py &
  - sleep 5
  - pytest tests/test_htsget_server.py

env:
  - HTSGET_TEST_KEY=thisisatest USE_MINIO_SANDBOX=True