language: python
dist: focal
python:
  - 3.10

services:
  - docker

env:
  - MINIO_ROOT_USER=minioadmin MINIO_ROOT_PASSWORD=minioadmin MINIO_URL=http://localhost:9000 MINIO_ACCESS_KEY=minioadmin MINIO_SECRET_KEY=minioadmin HTSGET_TEST_KEY=thisisatest USE_MINIO_SANDBOX=True DB_PATH=data/files.db

before_install:
  - docker pull minio/minio
  - docker create -p9090:9090 -p9000:9000 -p9001:9001 minio/minio minio server /data | xargs -I{} docker start {}
  - docker ps -a

cache: pip
install:
  - pip install -r requirements.txt
  - sqlite3 data/files.db -init data/files.sql 'select * from variantfile;'

script:
  - python htsget_server/server.py &
  - sleep 5
  - pytest tests/test_htsget_server.py