swagger: '2.0'
info:
  description: An API implementing the htsget standard
  title: htsget application
  version: "1"
consumes:
  - application/json
produces:
  - application/json
paths:
  /reads:
    get:
      operationId: "operations.get_reads"
      summary: "Retrieve desired URIs in a variant format given an ID"
      parameters:
        - name: id
          in: query
          required: true
          type: string
          x-example: "HG02102"
        - name: reference_name
          in: query
          type: integer
          required: false
          x-example: 21
        - name: start
          in: query
          type: integer
          required: false
          x-example: 0
        - name: end
          in: query
          type: integer
          required: false
          x-example: 10,000,000
      responses:
        "200":
          description: return list of URIs
          schema:
            type: object
            properties:
              htsget:
                type: object
                properties:
                  format:
                    type: string
                  urls:
                    type: array
                    items:
                      type: object
                      properties:
                        url:
                          type: string
  /variants:
    get:
      operationId: "operations.get_variants"
      summary: "Retrieve desired URIs in a variant format given an ID"
      parameters:
        - name: id
          in: query
          required: true
          type: string
          x-example: "HG02102"
        - name: reference_name
          in: query
          type: integer
          required: false
          x-example: 21
        - name: start
          in: query
          type: integer
          required: false
          x-example: 0
        - name: end
          in: query
          type: integer
          required: false
          x-example: 10,000,000
      responses:
        "200":
          description: return list of URIs
          schema:
            type: object
            properties:
              htsget:
                type: object
                properties:
                  format:
                    type: string
                  urls:
                    type: array
                    items:
                      type: object
                      properties:
                        url:
                          type: string

  /data:
    get:
      operationId: "operations.get_data"
      summary: "Retrieve data from urls"
      parameters:
        - name: id
          in: query
          required: true
          type: string
          x-example: "HG02102"
        - name: format
          in: query
          type: string
          x-example: "VCF"
        - name: reference_name
          in: query
          type: string
          x-example: 21
        - name: start
          in: query
          type: integer
          x-example: 0
        - name: end
          in: query
          type: integer
          x-example: 10,000,000
      responses:
        "200":
          description: return data
          schema:
            type: array
            items:
              type: string
              format: binary
